### ISSUE TITLE
quick documentation note

### ISSUE THREAD

**Issue by paultopia** [gadfly361/soda-ash#3]
This is an awesome library, but it might be helpful to people to explicitly point out in the readme that they shouldn't also require reagent in their dependencies.  I made that mistake, and the closure compiler puked on advanced compilation, took a while to figure out...

**Comment by gadfly361** [comment]
@paultopia Thanks for bringing this up!  Instead of not requiring reagent, you should exclude react-with-addons when depending on soda-ash.  I added the following to the README:

```
[soda-ash "0.1.0-beta"
  :exclusions [cljsjs/react-with-addons]]
```

Also, I strongly recommend not depending on soda-ash yet. I am working on a _complete_ re-write that should 1) provide full class coverage (not just elements), and 2) be much simpler to use ... however, that means the current release is simply useless.
